# Generated by Django 5.0.6 on 2024-05-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_quiz', '0002_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
