# Generated by Django 5.0.6 on 2024-05-16 12:25

import culture_quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_quiz', '0004_alter_category_header_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=culture_quiz.models.question_image_upload_path),
        ),
    ]
